---
- name: Export all assets
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Export all assets
      awx.awx.export:
        controller_host: 'http://10.0.0.215:30408/'
        #validate_certs: false
        controller_username: 'admin'
        controller_password: 'siB24Bsr21yghE3SIMnPQtk3lGLNqB84'
        #job_templates: 'all'
        projects: 'migrate'
        #all: true
      register: export_output
      delegate_to: localhost

    - name: Save export to file
      copy:
        content: "{{ export_output['assets'] }}"
        dest: /etc/awx/exports/exportProject.json
      delegate_to: localhost

