---
- name: Export all assets
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Export all assets
      awx.awx.export:
        controller_host='https://10.14.1.42'
        validate_certs: false
        controller_username: 'admin'
        controller_password: 'X1mlSZRhVAxixdMASV8gQEcxFc5kHLnt'
        #job_templates: 'all'
        #projects: 'all'
        all: True
      register: export_output

    - name: Save export to file
      copy:
        content: "{{ export_output['assets'] }}"
        dest: export.json
