---
- name: Export all assets
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Export all assets
      awx.awx.export:
        #job_templates: 'all'
        #projects: 'all'
        all: True
      register: export_output

    - name: Save export to file
      copy:
        content: "{{ export_output['assets'] }}"
        dest: export.json
