---
- name: Run nmap
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: run_nmap
      shell: nmap -T4 -sn -oX - 10.14.0.0/24 
      register: nmap_data
      delegate_to: localhost
    - name: print data
      debug:
        msg: "{{nmap_data}}"
      
